#!/bin/bash

if [ "$(whoami)" != "root" ]; then
	echo "Sorry, this script must be executed with sudo or as root"
	exit 1
fi

curl -u pi:himi535 -s "http://kodi:9981/api/dvr/entry/grid_upcoming?limit=99999%22" | grep -q '"sched_status":"recording",'

if [ "$?" -eq "0" ]; then
  echo "Recording is running!"
  exit 1
else
  grep "HDMI-CONFIG" /boot/firmware/config.txt

  if [ "$?" -eq "0" ]; then
    cp /boot/firmware/config.DSI /boot/firmware/config.txt 
    echo "Switch to DSI"
  else
    cp /boot/firmware/config.HDMI /boot/firmware/config.txt
    echo "Switch to HDMI"
  fi
  reboot
fi
